add bank factory interface duo to make creation of bank factory cleaner and shorter
ali-zahedi/az-iranian-bank-gateways pull request #116
Opened 2024-08-05 11:09 UTC by mojtabaakbari221b

برای ساختن یک instance از روی bank factory، نیاز به نوشتن کد زیاد و تکراری بود. همه‌ی این کارهارو بردم توی یه interface تا کار ساختن یه instance ساده تر انجام بشه.
دلیل اینکه توی یه فایل جدا نوشتم هم این بود چون خیلیا با ورژن قبلی راحت‌ترن، بعد آپدیت نیاز نباشه مجدد کدشون رو دست بزنند

2024-10-04 12:37 UTC, birddevelper commented
ممنون از مشارکت ارزشمند شما @mojtabaakbari221b 
لطفا برنچ خودتون رو با اخرین تغییرات برنچ main ریپازیتوری اصلی ریبیس کنید تا امکان مرج کردن داشته باشیم.

2024-10-04 12:37 UTC, birddevelper requested changes

2024-10-04 12:37 UTC, birddevelper commented on README.md
> +        return bank.redirect_gateway()
لطفا در مثالتون قبل از فراخوانی redirect_gateway متد ready رو هم اضافه کنید تا اگر کسی از مثال شما استفاده کرد به مشکل بر نخوره. 
```python
# ...
bank_record = bank.ready()
return bank.redirect_gateway()
# ...
```

2024-10-14 18:11 UTC, mojtabaakbari221b commented
تغییراتی که گفتید رو اعمال کردم. ممنونم از شما

2024-10-16 19:11 UTC, birddevelper approved these changes

2024-10-16 19:31 UTC, birddevelper commented
تشکر آقای اکبری عزیز. @mojtabaakbari221b

2024-10-24 14:20 UTC, merged